# -*- coding: utf-8 -*-
#!/usr/bin/env sage
"""
Recherche pour d = 53 (ℚ(√53)) avec D ∈ [1000, 5000]
Le vrai candidat fondamental !
"""


# This file was *autogenerated* from the file /home/bruno_dd/Téléchargements/isotopes_L72/d53_search.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0p06613695904451328 = RealNumber('0.06613695904451328'); _sage_const_0p28174250870863576 = RealNumber('0.28174250870863576'); _sage_const_0p5558698717637468 = RealNumber('0.5558698717637468'); _sage_const_0p8682439499340019 = RealNumber('0.8682439499340019'); _sage_const_1p5041139699699269 = RealNumber('1.5041139699699269'); _sage_const_1p7252596926363315 = RealNumber('1.7252596926363315'); _sage_const_1p831267929898219 = RealNumber('1.831267929898219'); _sage_const_2p0174227816393127 = RealNumber('2.0174227816393127'); _sage_const_2p092837042770219 = RealNumber('2.092837042770219'); _sage_const_2p524927313875301 = RealNumber('2.524927313875301'); _sage_const_3p279177783 = RealNumber('3.279177783'); _sage_const_3p851477234958053 = RealNumber('3.851477234958053'); _sage_const_4p571556651552703 = RealNumber('4.571556651552703'); _sage_const_4p724739892029763 = RealNumber('4.724739892029763'); _sage_const_7p407963149728111 = RealNumber('7.407963149728111'); _sage_const_1000 = Integer(1000); _sage_const_5000 = Integer(5000); _sage_const_20000 = Integer(20000); _sage_const_1en8 = RealNumber('1e-8'); _sage_const_53 = Integer(53); _sage_const_0p0 = RealNumber('0.0'); _sage_const_100 = Integer(100); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10); _sage_const_80 = Integer(80); _sage_const_3 = Integer(3); _sage_const_200 = Integer(200); _sage_const_60 = Integer(60); _sage_const_40 = Integer(40); _sage_const_20 = Integer(20); _sage_const_50 = Integer(50); _sage_const_5 = Integer(5); _sage_const_1500 = Integer(1500); _sage_const_2000 = Integer(2000); _sage_const_2500 = Integer(2500); _sage_const_3000 = Integer(3000); _sage_const_3500 = Integer(3500); _sage_const_4000 = Integer(4000); _sage_const_4500 = Integer(4500)
from sage.all import *
import time
import csv
import os

# =============================================================================
# CONFIGURATION
# =============================================================================

BETA_VALUES = [
    _sage_const_0p06613695904451328 , _sage_const_0p28174250870863576 , _sage_const_0p5558698717637468 ,
    _sage_const_0p8682439499340019 , _sage_const_1p5041139699699269 , _sage_const_1p7252596926363315 ,
    _sage_const_1p831267929898219 , _sage_const_2p0174227816393127 , _sage_const_2p092837042770219 ,
    _sage_const_2p524927313875301 , _sage_const_3p279177783 , _sage_const_3p851477234958053 ,
    _sage_const_4p571556651552703 , _sage_const_4p724739892029763 , _sage_const_7p407963149728111 
]

D_MIN = _sage_const_1000 
D_MAX = _sage_const_5000 
MAX_COEFF = _sage_const_20000   # Réduit car D est plus petit
ERR_THRESHOLD = _sage_const_1en8 

d = _sage_const_53 

OUTPUT_CSV = f"d_{d}_D_{D_MIN}_to_{D_MAX}.csv"

# =============================================================================
# TEST POUR UN D
# =============================================================================

def test_single_D(D):
    """Teste si D fonctionne pour tous les β"""
    sqrt_d = RR(d).sqrt()
    
    max_err = _sage_const_0p0 
    total_err = _sage_const_0p0 
    results = []
    
    for k, beta in enumerate(BETA_VALUES):
        target = beta * D
        b_center = int(target / sqrt_d)
        search_radius = _sage_const_100   # Plus petit car D est plus petit
        
        best_err = float('inf')
        best_pair = None
        
        for offset in range(-search_radius, search_radius + _sage_const_1 ):
            b = b_center + offset
            if abs(b) > MAX_COEFF:
                continue
            
            a_approx = target - b * sqrt_d
            a = round(a_approx)
            
            if abs(a) > MAX_COEFF:
                continue
            
            approx = (a + b * sqrt_d) / D
            err = abs(approx - beta) / beta if beta != _sage_const_0  else abs(approx)
            
            if err < best_err:
                best_err = err
                best_pair = (int(a), int(b))
                if best_err < ERR_THRESHOLD / _sage_const_10 :
                    break
        
        if best_pair and best_err < ERR_THRESHOLD:
            results.append({
                'k': k,
                'a': best_pair[_sage_const_0 ],
                'b': best_pair[_sage_const_1 ],
                'err': best_err
            })
            max_err = max(max_err, best_err)
            total_err += best_err
        else:
            return None
    
    avg_err = total_err / len(BETA_VALUES)
    return {
        'D': D,
        'max_err': max_err,
        'avg_err': avg_err,
        'results': results
    }

# =============================================================================
# MAIN
# =============================================================================

def main():
    print("=" * _sage_const_80 )
    print(f"🔍 RECHERCHE POUR d = {d} (ℚ(√53))")
    print(f"   D ∈ [{D_MIN}, {D_MAX}]")
    print("=" * _sage_const_80 )
    print(f"⚙️  √53 = {RR(d).sqrt():.10f}")
    print(f"⚙️  Seuil: {ERR_THRESHOLD:.0e}")
    print(f"⚙️  |a|,|b| ≤ {MAX_COEFF}")
    print()
    
    # Créer CSV
    with open(OUTPUT_CSV, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=[
            'D', 'max_err', 'avg_err', 'top_pairs'
        ])
        writer.writeheader()
    
    found = []
    nb_tests = D_MAX - D_MIN + _sage_const_1 
    
    print("📊 Recherche en cours...")
    start_time = time.time()
    
    for D in range(D_MIN, D_MAX + _sage_const_1 ):
        result = test_single_D(D)
        if result:
            found.append(result)
            
            # Sauvegarde immédiate
            top_pairs = [f"β_{r['k']}:({r['a']},{r['b']})" for r in result['results'][:_sage_const_3 ]]
            with open(OUTPUT_CSV, 'a', newline='') as f:
                writer = csv.DictWriter(f, fieldnames=['D', 'max_err', 'avg_err', 'top_pairs'])
                writer.writerow({
                    'D': D,
                    'max_err': result['max_err'],
                    'avg_err': result['avg_err'],
                    'top_pairs': "; ".join(top_pairs)
                })
        
        # Progression
        if (D - D_MIN + _sage_const_1 ) % _sage_const_200  == _sage_const_0  or D == D_MAX:
            elapsed = time.time() - start_time
            rate = (D - D_MIN + _sage_const_1 ) / elapsed if elapsed > _sage_const_0  else _sage_const_0 
            eta = (nb_tests - (D - D_MIN + _sage_const_1 )) / rate if rate > _sage_const_0  else _sage_const_0 
    
    print()  # Nouvelle ligne
    
    # =========================================================================
    # SYNTHÈSE
    # =========================================================================
    print("\n" + "=" * _sage_const_80 )
    print("📊 SYNTHÈSE FINALE")
    print("=" * _sage_const_80 )
    
    if found:
        # Trier par max_err
        found.sort(key=lambda x: x['max_err'])
        
        
        print("\n🏆 TOP 20 DES MEILLEURS D :")
        print("   D      | max_err    | avg_err")
        print("   " + "-" * _sage_const_40 )
        
        for res in found[:_sage_const_20 ]:
            print(f"   {res['D']:5d} | {res['max_err']:.2e} | {res['avg_err']:.2e}")
        
        # Champion
        best = found[_sage_const_0 ]
        print("\n" + "=" * _sage_const_80 )
        print(f"🏆 CHAMPION POUR d = {d} :")
        print(f"   D = {best['D']}")
        print(f"   max_err = {best['max_err']:.2e}")
        print(f"   avg_err = {best['avg_err']:.2e}")
        print("=" * _sage_const_80 )
        
        # Vérification détaillée du champion
        print("\n📝 VÉRIFICATION DÉTAILLÉE DU CHAMPION :")
        print(f"   d = {d}, D = {best['D']}")
        print("   " + "-" * _sage_const_50 )
        
        sqrt_d = RR(d).sqrt()
        for r in best['results'][:_sage_const_5 ]:  # Afficher les 5 premiers
            beta = BETA_VALUES[r['k']]
            approx = (r['a'] + r['b'] * sqrt_d) / best['D']
            print(f"   β_{r['k']:2d} ≈ ({r['a']:5d} + {r['b']:5d}√{d})/{best['D']}")
            print(f"        = {approx:.10f} | err = {r['err']:.2e}")
        
        # Statistiques sur les D
        D_values = [r['D'] for r in found]
        print("\n📊 STATISTIQUES SUR LES D TROUVÉS :")
        print(f"   Min D = {min(D_values)}")
        print(f"   Max D = {max(D_values)}")
        print(f"   Moyenne = {sum(D_values)/len(D_values):.1f}")
        
        # Regroupement par intervals
        print("\n📈 Distribution des D :")
        intervals = [(_sage_const_1000 , _sage_const_1500 ), (_sage_const_1500 , _sage_const_2000 ), (_sage_const_2000 , _sage_const_2500 ), (_sage_const_2500 , _sage_const_3000 ), 
                     (_sage_const_3000 , _sage_const_3500 ), (_sage_const_3500 , _sage_const_4000 ), (_sage_const_4000 , _sage_const_4500 ), (_sage_const_4500 , _sage_const_5000 )]
        for lo, hi in intervals:
            count = sum(_sage_const_1  for D in D_values if lo <= D < hi)
            if count > _sage_const_0 :
                print(f"   [{lo:4d}, {hi:4d}[ : {count:2d} D")
        
    else:
        print(f"❌ Aucun D trouvé dans [{D_MIN}, {D_MAX}]")
        print(f"   Essayez avec un intervalle différent")
    
    elapsed = time.time() - start_time
    print(f"\n⏱️  Temps total: {elapsed:.1f} secondes ({elapsed/_sage_const_60 :.1f} minutes)")
    print(f"💾 Résultats dans : {OUTPUT_CSV}")

if __name__ == "__main__":
    main()

