# -*- coding: utf-8 -*-
#!/usr/bin/env sage
"""
Recherche pour d = 53 avec D ∈ [14000, 17000]
Prédiction basée sur la proportionnalité D/facteur ≈ 15600
"""


# This file was *autogenerated* from the file /home/bruno_dd/Téléchargements/isotopes_L72/d53_search2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0p06613695904451328 = RealNumber('0.06613695904451328'); _sage_const_0p28174250870863576 = RealNumber('0.28174250870863576'); _sage_const_0p5558698717637468 = RealNumber('0.5558698717637468'); _sage_const_0p8682439499340019 = RealNumber('0.8682439499340019'); _sage_const_1p5041139699699269 = RealNumber('1.5041139699699269'); _sage_const_1p7252596926363315 = RealNumber('1.7252596926363315'); _sage_const_1p831267929898219 = RealNumber('1.831267929898219'); _sage_const_2p0174227816393127 = RealNumber('2.0174227816393127'); _sage_const_2p092837042770219 = RealNumber('2.092837042770219'); _sage_const_2p524927313875301 = RealNumber('2.524927313875301'); _sage_const_3p279177783 = RealNumber('3.279177783'); _sage_const_3p851477234958053 = RealNumber('3.851477234958053'); _sage_const_4p571556651552703 = RealNumber('4.571556651552703'); _sage_const_4p724739892029763 = RealNumber('4.724739892029763'); _sage_const_7p407963149728111 = RealNumber('7.407963149728111'); _sage_const_14000 = Integer(14000); _sage_const_17000 = Integer(17000); _sage_const_50000 = Integer(50000); _sage_const_1en8 = RealNumber('1e-8'); _sage_const_53 = Integer(53); _sage_const_80 = Integer(80); _sage_const_1 = Integer(1); _sage_const_200 = Integer(200); _sage_const_201 = Integer(201); _sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_60 = Integer(60)
from sage.all import *
import time

BETA_VALUES = [
    _sage_const_0p06613695904451328 , _sage_const_0p28174250870863576 , _sage_const_0p5558698717637468 ,
    _sage_const_0p8682439499340019 , _sage_const_1p5041139699699269 , _sage_const_1p7252596926363315 ,
    _sage_const_1p831267929898219 , _sage_const_2p0174227816393127 , _sage_const_2p092837042770219 ,
    _sage_const_2p524927313875301 , _sage_const_3p279177783 , _sage_const_3p851477234958053 ,
    _sage_const_4p571556651552703 , _sage_const_4p724739892029763 , _sage_const_7p407963149728111 
]

D_MIN = _sage_const_14000 
D_MAX = _sage_const_17000 
MAX_COEFF = _sage_const_50000 
ERR_THRESHOLD = _sage_const_1en8 
d = _sage_const_53 

print("=" * _sage_const_80 )
print(f"🔍 RECHERCHE POUR d = {d} (ℚ(√53))")
print(f"   D ∈ [{D_MIN}, {D_MAX}]")
print("=" * _sage_const_80 )

sqrt_d = RR(d).sqrt()
found = []
nb_tests = D_MAX - D_MIN + _sage_const_1 

start_time = time.time()

for D in range(D_MIN, D_MAX + _sage_const_1 ):
    success = True
    for beta in BETA_VALUES:
        target = beta * D
        b_center = int(target / sqrt_d)
        best_err = float('inf')
        
        for offset in range(-_sage_const_200 , _sage_const_201 ):
            b = b_center + offset
            if abs(b) > MAX_COEFF:
                continue
            a = round(target - b * sqrt_d)
            if abs(a) > MAX_COEFF:
                continue
            approx = (a + b * sqrt_d) / D
            err = abs(approx - beta) / beta
            if err < best_err:
                best_err = err
            if best_err < ERR_THRESHOLD / _sage_const_10 :
                break
        
        if best_err >= ERR_THRESHOLD:
            success = False
            break
    
    if success:
        found.append(D)
        print(f"   ✅ D = {D} trouvé !")
    
    if (D - D_MIN + _sage_const_1 ) % _sage_const_200  == _sage_const_0 :
        elapsed = time.time() - start_time

if found:
    print(f"📊 D trouvés : {found}")
else:
    print("❌ Aucun D trouvé")

print(f"⏱️  Temps: {(time.time()-start_time)/_sage_const_60 :.1f} min")

