

# This file was *autogenerated* from the file /home/bruno_dd/Téléchargements/isotopes_L72/search_target_fields2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_6400 = Integer(6400); _sage_const_53 = Integer(53); _sage_const_6800 = Integer(6800); _sage_const_1 = Integer(1); _sage_const_33 = Integer(33)# Calcul des candidats potentiels
import math

# Pour √53 : d = 53 × k²
k = range(int(math.sqrt(_sage_const_6400 /_sage_const_53 )), int(math.sqrt(_sage_const_6800 /_sage_const_53 )) + _sage_const_1 )
print("Candidats pour √53:")
for k in k:
    d = _sage_const_53  * k * k
    if _sage_const_6400  <= d <= _sage_const_6800 :
        print(f"  d = {d} = 53 × {k}² = 53 × {k*k}")

# Pour √33 : d = 33 × k²
k = range(int(math.sqrt(_sage_const_6400 /_sage_const_33 )), int(math.sqrt(_sage_const_6800 /_sage_const_33 )) + _sage_const_1 )
print("\nCandidats pour √33:")
for k in k:
    d = _sage_const_33  * k * k
    if _sage_const_6400  <= d <= _sage_const_6800 :
        print(f"  d = {d} = 33 × {k}² = 33 × {k*k}")

