# -*- coding: utf-8 -*-
#!/usr/bin/env sage
"""
Recherche systématique pour ℚ(√53) avec différents facteurs carrés
d = 53 × k² pour k = 1 à 30
Recherche des D ∈ [78000, 79500] qui fonctionnent
"""


# This file was *autogenerated* from the file /home/bruno_dd/Téléchargements/isotopes_L72/sqrt53_all_k.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0p06613695904451328 = RealNumber('0.06613695904451328'); _sage_const_0p28174250870863576 = RealNumber('0.28174250870863576'); _sage_const_0p5558698717637468 = RealNumber('0.5558698717637468'); _sage_const_0p8682439499340019 = RealNumber('0.8682439499340019'); _sage_const_1p5041139699699269 = RealNumber('1.5041139699699269'); _sage_const_1p7252596926363315 = RealNumber('1.7252596926363315'); _sage_const_1p831267929898219 = RealNumber('1.831267929898219'); _sage_const_2p0174227816393127 = RealNumber('2.0174227816393127'); _sage_const_2p092837042770219 = RealNumber('2.092837042770219'); _sage_const_2p524927313875301 = RealNumber('2.524927313875301'); _sage_const_3p279177783 = RealNumber('3.279177783'); _sage_const_3p851477234958053 = RealNumber('3.851477234958053'); _sage_const_4p571556651552703 = RealNumber('4.571556651552703'); _sage_const_4p724739892029763 = RealNumber('4.724739892029763'); _sage_const_7p407963149728111 = RealNumber('7.407963149728111'); _sage_const_78000 = Integer(78000); _sage_const_79500 = Integer(79500); _sage_const_200000 = Integer(200000); _sage_const_1en8 = RealNumber('1e-8'); _sage_const_1 = Integer(1); _sage_const_31 = Integer(31); _sage_const_0p0 = RealNumber('0.0'); _sage_const_200 = Integer(200); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10); _sage_const_53 = Integer(53); _sage_const_300 = Integer(300); _sage_const_20 = Integer(20); _sage_const_80 = Integer(80); _sage_const_60 = Integer(60); _sage_const_48 = Integer(48)
from sage.all import *
import time
import csv
import os

# =============================================================================
# CONFIGURATION
# =============================================================================

BETA_VALUES = [
    _sage_const_0p06613695904451328 , _sage_const_0p28174250870863576 , _sage_const_0p5558698717637468 ,
    _sage_const_0p8682439499340019 , _sage_const_1p5041139699699269 , _sage_const_1p7252596926363315 ,
    _sage_const_1p831267929898219 , _sage_const_2p0174227816393127 , _sage_const_2p092837042770219 ,
    _sage_const_2p524927313875301 , _sage_const_3p279177783 , _sage_const_3p851477234958053 ,
    _sage_const_4p571556651552703 , _sage_const_4p724739892029763 , _sage_const_7p407963149728111 
]

D_MIN = _sage_const_78000 
D_MAX = _sage_const_79500 
MAX_COEFF = _sage_const_200000 
ERR_THRESHOLD = _sage_const_1en8 

# k de 1 à 30 (d = 53 × k²)
K_VALUES = range(_sage_const_1 , _sage_const_31 )

OUTPUT_CSV = "sqrt53_all_k.csv"

# =============================================================================
# TEST POUR UN (d, D)
# =============================================================================

def test_single_pair(d, D):
    """Teste si (d, D) fonctionne pour tous les β"""
    sqrt_d = RR(d).sqrt()
    
    max_err = _sage_const_0p0 
    total_err = _sage_const_0p0 
    results = []
    
    for k, beta in enumerate(BETA_VALUES):
        target = beta * D
        b_center = int(target / sqrt_d)
        search_radius = _sage_const_200 
        
        best_err = float('inf')
        best_pair = None
        
        for offset in range(-search_radius, search_radius + _sage_const_1 ):
            b = b_center + offset
            if abs(b) > MAX_COEFF:
                continue
            
            a_approx = target - b * sqrt_d
            a = round(a_approx)
            
            if abs(a) > MAX_COEFF:
                continue
            
            approx = (a + b * sqrt_d) / D
            err = abs(approx - beta) / beta if beta != _sage_const_0  else abs(approx)
            
            if err < best_err:
                best_err = err
                best_pair = (int(a), int(b))
                if best_err < ERR_THRESHOLD / _sage_const_10 :
                    break
        
        if best_pair and best_err < ERR_THRESHOLD:
            results.append({
                'k': k,
                'a': best_pair[_sage_const_0 ],
                'b': best_pair[_sage_const_1 ],
                'err': best_err
            })
            max_err = max(max_err, best_err)
            total_err += best_err
        else:
            return None
    
    avg_err = total_err / len(BETA_VALUES)
    return {
        'd': d,
        'D': D,
        'max_err': max_err,
        'avg_err': avg_err,
        'results': results
    }

# =============================================================================
# RECHERCHE POUR UN d DONNÉ
# =============================================================================

def search_d_for_d(d):
    """Recherche tous les D pour un d donné"""
    print(f"\n  Test d = {d} (k = {int(sqrt(d/_sage_const_53 ))})...")
    
    found = []
    nb_tests = D_MAX - D_MIN + _sage_const_1 
    
    for D in range(D_MIN, D_MAX + _sage_const_1 ):
        result = test_single_pair(d, D)
        if result:
            found.append(result)
        
        # Progression
        if (D - D_MIN + _sage_const_1 ) % _sage_const_300  == _sage_const_0 :
    
    return found

# =============================================================================
# MAIN
# =============================================================================

def main():
    print("=" * _sage_const_80 )
    print("🔍 RECHERCHE SYSTÉMATIQUE POUR ℚ(√53)")
    print("   d = 53 × k² pour k = 1 à 30")
    print("=" * _sage_const_80 )
    print(f"📐 D ∈ [{D_MIN}, {D_MAX}]")
    print(f"⚙️  Seuil: {ERR_THRESHOLD:.0e}")
    print()
    
    # Créer CSV
    with open(OUTPUT_CSV, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=[
            'k', 'd', 'nb_Ds_found', 'best_D', 'max_err', 'avg_err', 'all_Ds'
        ])
        writer.writeheader()
    
    all_results = []
    
    for k in K_VALUES:
        d = _sage_const_53  * k * k
        print(f"\n{'='*_sage_const_60 }")
        print(f"📐 k = {k:2d} | d = {d}")
        
        found = search_d_for_d(d)
        
        if found:
            found.sort(key=lambda x: x['max_err'])
            best = found[_sage_const_0 ]
            all_Ds = [r['D'] for r in found]
            
            with open(OUTPUT_CSV, 'a', newline='') as f:
                writer = csv.DictWriter(f, fieldnames=[
                    'k', 'd', 'nb_Ds_found', 'best_D', 'max_err', 'avg_err', 'all_Ds'
                ])
                writer.writerow({
                    'k': k,
                    'd': d,
                    'nb_Ds_found': len(found),
                    'best_D': best['D'],
                    'max_err': best['max_err'],
                    'avg_err': best['avg_err'],
                    'all_Ds': str(all_Ds)
                })
            
            all_results.append({
                'k': k,
                'd': d,
                'nb_Ds': len(found),
                'best_D': best['D'],
                'max_err': best['max_err']
            })
            
            print(f"\n  ✅ {len(found)} D trouvés !")
            print(f"     Meilleur D = {best['D']} | max_err = {best['max_err']:.2e}")
            print(f"     Tous les D : {all_Ds[:_sage_const_10 ]}" + ("..." if len(all_Ds) > _sage_const_10  else ""))
        else:
            print(f"\n  ❌ Aucun D trouvé")
    
    # =========================================================================
    # SYNTHÈSE
    # =========================================================================
    print("\n" + "=" * _sage_const_80 )
    print("📊 SYNTHÈSE FINALE")
    print("=" * _sage_const_80 )
    
    if all_results:
        # Trier par nb_Ds décroissant
        all_results.sort(key=lambda x: x['nb_Ds'], reverse=True)
        
        print("\n🏆 Classement par nombre de D trouvés :")
        print("   k | d        | nb_Ds | best_D   | max_err")
        print("   " + "-" * _sage_const_48 )
        
        for res in all_results:
            print(f"   {res['k']:2d} | {res['d']:8d} | {res['nb_Ds']:5d} | {res['best_D']:7d} | {res['max_err']:.2e}")
        
        # Champion
        best = all_results[_sage_const_0 ]
        print("\n" + "=" * _sage_const_80 )
        print(f"🏆 CHAMPION POUR ℚ(√53) :")
        print(f"   k = {best['k']} | d = {best['d']}")
        print(f"   nb_Ds = {best['nb_Ds']} | best_D = {best['best_D']}")
        print(f"   max_err = {best['max_err']:.2e}")
        print("=" * _sage_const_80 )
    else:
        print("❌ Aucun résultat trouvé")
    
    print(f"\n💾 Résultats dans : {OUTPUT_CSV}")

if __name__ == "__main__":
    main()

