

# This file was *autogenerated* from the file /home/bruno_dd/Téléchargements/isotopes_L72/vérif.sage
from sage.all_cmdline import *   # import sage library

_sage_const_6772 = Integer(6772); _sage_const_6787 = Integer(6787); _sage_const_6698 = Integer(6698); _sage_const_6625 = Integer(6625)# Vérification rapide
ds_with_4_D = [_sage_const_6772 , _sage_const_6787 , _sage_const_6698 , _sage_const_6625 ]
for d in ds_with_4_D:
    print(f"{d} = {factor(d)}")

