

# This file was *autogenerated* from the file /home/bruno_dd/Téléchargements/isotopes_L72/vérif2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_6468 = Integer(6468); _sage_const_6771 = Integer(6771); _sage_const_6714 = Integer(6714)# Dans Sage
ds_with_3_D = [_sage_const_6468 , _sage_const_6771 , _sage_const_6714 ]
for d in ds_with_3_D:
    print(f"{d} = {factor(d)}")

